### ISSUE TITLE
Any binary releases?

### ISSUE THREAD

**Issue by luochen1990** [mickbeaver/win32emacslauncher#1]
I failed to build it via g++,  following is the message:

```
$ g++ main.cpp -o emacs
C:/dev/mingw-w64/x86_64-6.3.0-posix-seh-rt_v5-rev1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x2e): undefined reference to `WinMain'
collect2.exe: error: ld returned 1 exit status
```

Is there any binary releases?

**Comment by mickbeaver** [comment]
Hello,

I believe you need to use the -municode option with MinGW.

If you want a pre-compiled binary, you can have mine at http://pages.cs.wisc.edu/~mick/downloads/edit.exe (I don't recall which version of Visual Studio I used, though).
